[package]
name = "Wormhole"
version = "0.0.1"

[dependencies]
# sui v0.18.0
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "a8af20d94e951ecfb6d0cd47c23cf6393013d8a8" }

[addresses]
wormhole = "0x0"
