[package]
name = "TokenBridge"
version = "0.0.1"
published-at = "0x1"

[addresses]
token_bridge = "0x1"
wormhole = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "cab7e9762d4d75126a78fdd009b405745657fe57"
rev = "3a70c4374090b020b95465787f3220a95d8ab0ba"

[dependencies.Wormhole]
local = "../wormhole"

#
#[dev-dependencies.Wormhole]
#local = "../wormhole"
#
#[dev-addresses]
#wormhole = "0x100"
#token_bridge = "0x200"
