import { ChainId } from "@certusone/wormhole-sdk";

export const chainIDStrings: { [key in ChainId]: string } = {
  0: "Unset",
  1: "Solana",
  2: "Ethereum",
  3: "Terra",
  4: "BSC",
  5: "Polygon",
  6: "Avalanche",
  7: "Oasis",
  8: "Algorand",
  9: "Aurora",
  10: "Fantom",
  11: "Karura",
  12: "Acala",
  13: "Klaytn",
  14: "Celo",
  15: "NEAR",
  16: "Moonbeam",
  17: "Neon",
  18: "Terra2",
  19: "Injective",
  20: "Osmosis",
  21: "Sui",
  22: "Aptos",
  23: "Arbitrum",
  24: "Optimism",
  25: "Gnosis",
  26: "Pythnet",
  28: "Xpla",
  10001: "Ropsten",
  3104: "Wormholechain",
};
